# settings.yaml
box_name: "bento/ubuntu-23.10"
vm:
- name: "controlplane"
  ip: "192.168.56.10"
  memory: "2048"
  cpus: "2"
- name: "node01"
  ip: "192.168.56.11"
  memory: "1024"
  cpus: "1"
- name: "node02"
  ip: "192.168.56.12"
  memory: "1024"
  cpus: "1"
